# Generated by Django 3.2.12 on 2022-04-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0003_auto_20220415_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('id',)},
        ),
    ]
